### ISSUE TITLE
Code input text font size

### ISSUE THREAD

**Issue by jusmop** [jcooper-korg/AlarmPanel#14]
This is not a bug report - just a request for assistance.

I have customised the UI of this alarm panel more-or-less successfully but there is one change I'm struggling with. I'm trying to make the code input box text larger and also have the text "Code" be on the same line as the hidden password. I have made the box itself wider.

Adding a font-size value to the ha-textfield css string (around line 575) does not have any effect. Does anyone know how to enlarge the font?

Thanks for sharing the card, i've found it very useful - particularly the timer.

**Comment by jcooper-korg** [comment]
I'm not sure how to style this. I've experimented with it too, without much luck.
I'm using the same password code field as the standard HA password field:

https://github.com/home-assistant/frontend/blob/811c34b489f25ba54cb1cef29b6d2b1d40365803/src/panels/lovelace/cards/hui-alarm-panel-card.ts#L280-L287

https://github.com/home-assistant/frontend/blob/811c34b489f25ba54cb1cef29b6d2b1d40365803/src/panels/lovelace/cards/hui-alarm-panel-card.ts#L401-L406

if you figure out any improvement, please let me know!

**Comment by jusmop** [comment]
Thanks for the links. Material Design Components? What are they? (rhetorical question - I'm well out of my depth here). I'll persevere for a bit... If I get anywhere I'll let you know.

**Comment by jcooper-korg** [comment]
There's some info here:  https://design.home-assistant.io/#concepts/home
may be able to ask on the ux dev discord.

**Comment by jusmop** [comment]
I found a possible solution:

Insert a new line before line 460:
        --mdc-typography-subtitle1-font-size: 24px;

I found the variable using the Chrome style inspector for a dashboard page with the custom alarm card on it. I have no idea if it has unwanted side effects (ideally it only applies to that card), but it changes the font size for me.

**Comment by jcooper-korg** [comment]
Good find!  Thanks!  
Rather than putting that in the ha-card section of the css, how about constraining it to be just in the ha-textfield section:  https://github.com/jcooper-korg/AlarmPanel/blob/18a92d882c3eb9dab3fdb3869b46bced307821bb/alarm_control_panel-card.js#L572-L577

I tried adding it there, and it works!  Thanks again

**Comment by jcooper-korg** [comment]
thanks again @jusmop - I added that change in ceeffdb
