### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'manual'. 

### ISSUE THREAD

**Issue by giangi007** [jcooper-korg/AlarmPanel#2]
Hello, could you fix this issue?
No 'version' key in the manifest file for custom integration 'manual'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'manual'
![Immagine 2021-03-16 195109](https://user-images.githubusercontent.com/15632171/111363974-f9d79580-8690-11eb-8702-32d894cdc074.png)

Thanks in advance

**Comment by jcooper-korg** [comment]
I added it. Please try again with the updated manifest.json at https://github.com/jcooper-korg/core/tree/dev/homeassistant/components/manual
