### ISSUE TITLE
Uncaught syntax -  error

### ISSUE THREAD

**Issue by ijustlikeit** [jcooper-korg/AlarmPanel#5]
frontend_latest/app.d030393d.js:851:83917 Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'DocumentFragment': 'label[for = 3]' is not a valid selector.

I get these error messages in my log when the buttons are pushed for the alarm code.  So for example when I push 3 on the alarm pad it gives the message above.

Just started happening on core-2021.10.x.

**Comment by jcooper-korg** [comment]
Sorry for the delay- I'm finally looking at this!
I updated HA from 2021.8.1 to the latest 2021.12.1, and all seems well.  I don't see any errors in the log when running the alarm or pressing the buttons. 

That said, I see a potential issue in the code, and have pushed a change. Can you please pull it and give it a try? (make sure you clear your local caches, and bump the version in the dashboards/resources page, e.g. "/local/alarm_control_panel-card.js?v=3" to force it to load the updated js file.

**Comment by ijustlikeit** [comment]
Thanks for looking into this.
I've tried it and it works now.  No more errors.  
Thank you    @jcooper-korg  for the fix.   Have a great evening!
